[AppSettings]
FileFolder=/data/user-app/website/data/
QueueCheckIntervalSeconds=30
MaxQueueCheckIntervalSeconds=300

[LogSettings]
LogFileQuotaMBytes=5
LogFileSplits=3
LogFolder=/data/user-app/charging_data/log/
LogFile=charging_data.log

[RestApi]
Host=127.0.0.1
Port=5555

[Mqtt]
Host=127.0.0.1
Port=1883
User=
Password=

[EmmSettings]
Host=https://app.ewe.cz
ApiKey=
SessionEndpoint=/api/v2/public/charging-session
TelemetryEndpoint=/api/v2/public/controller-telemetry